### ISSUE TITLE
Can't save keywords and titles on later editions

### ISSUE THREAD

**Issue by Floppy** [theodi/publisher#135]
If a new edition of an article is created, we can't update keywords or title in publisher.

**Comment by Floppy** [comment]
Just titles now.

**Comment by gilesdring** [comment]
Result of investigation today:

When updating an `edition` in Publisher, updates may be triggered in Panopticon (esp. tags).
When this occurs [the govuk_content_models artefact after_update trigger](https://github.com/theodi/govuk_content_models/blob/master/app/models/artefact.rb#L116) will cause the [Artefact#update_editions](https://github.com/theodi/govuk_content_models/blob/master/app/models/artefact.rb#L242-L251) action to execute, which in turn calls [Edition#update_from_artefact](https://github.com/theodi/govuk_content_models/blob/master/app/models/edition.rb#L250-L257). This contains the code

    self.title = artefact.name unless published?

Which causes the `title` to be overwritten, as by definition, an edition which is being edited is not published.
This also updates the `slug`, `section`, `department` and `business_proposition`.

**Comment by gilesdring** [comment]
The changes in govuk_content_models are a red herring. Please ignore them. The fix is to monkey patch Editions in the odi_content_models to stop changes in panopticon updating the title of the Edition. Needs the odi_content_models gem to be reintegrated to all backend services...

**Comment by Floppy** [comment]
makes sense...

**Comment by gilesdring** [comment]
Erm... still need to do the Gemfile regeneration with `bundler update --source odi_content_models`. Is that part of deployment, or should I be doing PRs against the separate repos. Also, although it seems to work for Publisher, as soon as any change is made in Panopticon, it overwrites the title. I presume the monkey patch is not applying correctly, as I can see the updated gem code in `/usr/lib/bundle/...` Propose that this ought to be looked at in a little more depth.

**Comment by Floppy** [comment]
Ah, yes, that will need separate bundle updates on each of the apps.

**Comment by Floppy** [comment]
Right, done those two changes, so this should be OK now. Will test shortly.

**Comment by Floppy** [comment]
@langphil this should now be fixed, you should be able to edit titles in editions.

**Comment by langphil** [comment]
Thank you.

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 19 June 2015 at 15:24:57, James Smith (notifications@github.com) wrote:

@langphil this should now be fixed, you should be able to edit titles in editions.

**Comment by gilesdring** [comment]
I also have a branch https://github.com/theodi/publisher/tree/fix/publisher-135 on Github. This contains the updated guard on keyword updating - which I don't think is really required. Up to @floppy whether this gets merged or not.

**Comment by gilesdring** [comment]
This does seem to be working on Publisher, but if any change is made to tagging in Panopticon, the original issue recurs. This appears to be down to incorrect importing of the odi_content_models within Panopticon.

In the rails console, running `Edition.instance_method(:update_from_artefact).source_location` gives the following in Publisher:

    => ["/usr/local/bundle/bundler/gems/odi_content_models-0d9376730f8c/app/decorators/models/edition_decorator.rb", 20]

The same command in Panopticon gives:

    => ["/usr/local/bundle/gems/govuk_content_models-6.1.0/app/models/edition.rb", 250]
    irb(main):002:0>
